version: "3"

services:
#  cats-service:
#    build:
#      context: ./cats-service
#      dockerfile: Dockerfile
#    ports:
#      - "8091:8091"
#    depends_on:
#      - postgres

  postgres-cats:
    image: "postgres:15.1"
    restart: unless-stopped
    environment:
      POSTGRES_DB: "cats_database"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "12345678"
    volumes:
      - ./_databases/cats/init:/docker-entrypoint-initdb.d
      - cats_database:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    container_name: "postgres-cats"

  postgres-mice:
    image: "postgres:15.1"
    restart: unless-stopped
    environment:
      POSTGRES_DB: "mice_database"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "12345678"
    volumes:
      - ./_databases/mice/init:/docker-entrypoint-initdb.d
      - mice_database:/var/lib/postgresql/data
    ports:
      - "5434:5432"
    container_name: "postgres-mice"

volumes:
  cats_database:
    external: true
  mice_database:
    external: true

#  gateway:
#    build:
#      context: ./api-gateway
#      dockerfile: Dockerfile
#    ports:
#      - 8765:8765
#    environment:
#      - DISCOVERY_URL=http://discovery:8761
#    links:
#      - discovery
#      - authors
#      - authors_two
#      - articles
#      - articles_two
#    depends_on:
#      - discovery